services:
  web:
    build: .
    container_name: internship_matching_platform
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/internship_db
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: internship_matching_platform_db
    restart: always
    ports:
      - "5434:5432"  # host:container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=internship_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
