"""change user id column in VerificationCode Model to unique=True

Revision ID: 14f417b15c69
Revises: d400e5ab41bb
Create Date: 2025-09-06 11:39:06.786015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f417b15c69'
down_revision: Union[str, Sequence[str], None] = 'd400e5ab41bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'verification_code', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_code', type_='unique')
    # ### end Alembic commands ###
