"""edit datetime column for project

Revision ID: 1ee35eea40d9
Revises: fef96c00464b
Create Date: 2025-09-17 03:08:18.728124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ee35eea40d9"
down_revision: Union[str, Sequence[str], None] = "fef96c00464b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column("task", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("task", "is_completed", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("task", "is_submitted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("task", "due_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "task", "completed_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "task", "submitted_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "submitted_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "task", "completed_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("task", "due_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("task", "is_submitted", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("task", "is_completed", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("task", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "project",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
