"""add additional fields to verification code model

Revision ID: 26d9cc7a8558
Revises: a9fb2b8981d8
Create Date: 2025-09-09 07:54:29.487972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26d9cc7a8558"
down_revision: Union[str, Sequence[str], None] = "a9fb2b8981d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_code", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()"))
    )
    op.add_column(
        "verification_code", sa.Column("expires_at", sa.DateTime(), nullable=False, server_default=sa.text("now() + INTERVAL '15 minutes'"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification_code", "expires_at")
    op.drop_column("verification_code", "created_at")
    # ### end Alembic commands ###
