"""add is_completed and is_submitted fields to task

Revision ID: 30aca4b1063d
Revises: d1da2d07104d
Create Date: 2025-09-16 21:22:29.886919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30aca4b1063d"
down_revision: Union[str, Sequence[str], None] = "d1da2d07104d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("is_completed", sa.Boolean(), nullable=True))
    op.add_column("task", sa.Column("is_submitted", sa.Boolean(), nullable=True))
    op.add_column("task", sa.Column("completed_at", sa.DateTime(), nullable=True))
    op.add_column("task", sa.Column("submitted_at", sa.DateTime(), nullable=True))
    op.alter_column("user", "department_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "department_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("task", "submitted_at")
    op.drop_column("task", "completed_at")
    op.drop_column("task", "is_submitted")
    op.drop_column("task", "is_completed")
    # ### end Alembic commands ###
