"""add user_id to token table

Revision ID: 48d198d20ccf
Revises: 2aae53cfea78
Create Date: 2025-09-17 23:35:32.878259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d198d20ccf'
down_revision: Union[str, Sequence[str], None] = '2aae53cfea78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM token;")
    op.add_column('token', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'user_id')
    # ### end Alembic commands ###
