"""add school column to intern table

Revision ID: 64e02abcf18e
Revises: fe88785efeee
Create Date: 2025-09-10 17:57:35.896616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64e02abcf18e"
down_revision: Union[str, Sequence[str], None] = "fe88785efeee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("intern", sa.Column("school", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intern", "school")
    # ### end Alembic commands ###
