"""fix todo <-> intern relationship

Revision ID: 8cb3c8f82bb3
Revises: 8dc64676560b
Create Date: 2025-09-12 13:19:10.335250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb3c8f82bb3'
down_revision: Union[str, Sequence[str], None] = '8dc64676560b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('intern_id', sa.UUID(), nullable=False))
    op.add_column('todo', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('todo', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('todo', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('todo_user_id_fkey'), 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'intern', ['intern_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(op.f('todo_user_id_fkey'), 'todo', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('todo', 'updated_at')
    op.drop_column('todo', 'created_at')
    op.drop_column('todo', 'done')
    op.drop_column('todo', 'intern_id')
    # ### end Alembic commands ###
