"""remove department foreign key from supervisor

Revision ID: 8dc64676560b
Revises: b7ab3a731021
Create Date: 2025-09-09 13:56:51.135875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dc64676560b"
down_revision: Union[str, Sequence[str], None] = "b7ab3a731021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("supervisor_department_id_fkey"), "supervisor", type_="foreignkey"
    )
    op.drop_column("supervisor", "department_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supervisor",
        sa.Column("department_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("supervisor_department_id_fkey"),
        "supervisor",
        "department",
        ["department_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
