"""made user dob column non_nullable

Revision ID: a9fb2b8981d8
Revises: d9a4f802177c
Create Date: 2025-09-08 12:20:23.573199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fb2b8981d8'
down_revision: Union[str, Sequence[str], None] = 'd9a4f802177c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text(""" 
        UPDATE "user" SET date_of_birth = '1990-01-01' WHERE date_of_birth IS NULL
    """))

    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
