"""add new table to link intern and supervisor

Revision ID: b94cbe88a3aa
Revises: 8dc64676560b
Create Date: 2025-09-10 16:09:24.719126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94cbe88a3aa'
down_revision: Union[str, Sequence[str], None] = '8dc64676560b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intern_supervisor',
    sa.Column('intern_id', sa.UUID(), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=False),
    sa.Column('date_assigned', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['intern.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intern_id', 'supervisor_id')
    )
    op.drop_constraint(op.f('intern_supervisor_id_fkey'), 'intern', type_='foreignkey')
    op.drop_column('intern', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intern', sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('intern_supervisor_id_fkey'), 'intern', 'supervisor', ['supervisor_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_table('intern_supervisor')
    # ### end Alembic commands ###
