"""add normalized_email column to user model

Revision ID: bd3a6fc36231
Revises: 84d452fc6885
Create Date: 2025-09-09 08:41:08.804651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3a6fc36231'
down_revision: Union[str, Sequence[str], None] = '84d452fc6885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('normalized_email', sa.String()))
    op.execute(sa.text("""
        UPDATE "user" SET normalized_email = LOWER(email)
        """))
    op.alter_column('user', 'normalized_email', nullable=False)
    op.create_unique_constraint(None, 'user', ['normalized_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'normalized_email')
    # ### end Alembic commands ###
