"""Add verification code model

Revision ID: d400e5ab41bb
Revises: fdaf2669ee0f
Create Date: 2025-09-05 20:28:04.896892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d400e5ab41bb"
down_revision: Union[str, Sequence[str], None] = "fdaf2669ee0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_code",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.add_column("user", sa.Column("firstname", sa.String(length=50), nullable=False))
    op.add_column("user", sa.Column("lastname", sa.String(length=50), nullable=False))
    op.add_column(
        "user", sa.Column("phone_number", sa.String(length=15), nullable=False)
    )
    op.add_column("user", sa.Column("verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "verified")
    op.drop_column("user", "phone_number")
    op.drop_column("user", "lastname")
    op.drop_column("user", "firstname")
    op.drop_table("verification_code")
    # ### end Alembic commands ###
