"""add new attrs to intern model

Revision ID: d8c84a795eb7
Revises: 14f417b15c69
Create Date: 2025-09-06 15:41:41.484279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8c84a795eb7"
down_revision: Union[str, Sequence[str], None] = "14f417b15c69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("administrator_user_id_fkey"), "administrator", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "administrator",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("administrator", "name")
    op.add_column("intern", sa.Column("division_name", sa.String(), nullable=True))
    op.drop_constraint(op.f("intern_division_id_fkey"), "intern", type_="foreignkey")
    op.drop_constraint(op.f("intern_supervisor_id_fkey"), "intern", type_="foreignkey")
    op.drop_constraint(op.f("intern_user_id_fkey"), "intern", type_="foreignkey")
    op.create_foreign_key(
        None,
        "intern",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "intern",
        "division",
        ["division_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "intern",
        "supervisor",
        ["supervisor_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.drop_column("intern", "division_id")
    op.drop_column("intern", "name")
    op.add_column("supervisor", sa.Column("division_name", sa.String(), nullable=True))
    op.drop_constraint(
        op.f("supervisor_user_id_fkey"), "supervisor", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("supervisor_division_id_fkey"), "supervisor", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "supervisor",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "supervisor",
        "division",
        ["division_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.drop_column("supervisor", "division_id")
    op.drop_column("supervisor", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supervisor",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "supervisor",
        sa.Column("division_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "supervisor", type_="foreignkey")
    op.drop_constraint(None, "supervisor", type_="foreignkey")
    op.create_foreign_key(
        op.f("supervisor_division_id_fkey"),
        "supervisor",
        "division",
        ["division_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("supervisor_user_id_fkey"), "supervisor", "user", ["user_id"], ["id"]
    )
    op.drop_column("supervisor", "division_name")
    op.add_column(
        "intern", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "intern",
        sa.Column("division_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "intern", type_="foreignkey")
    op.drop_constraint(None, "intern", type_="foreignkey")
    op.drop_constraint(None, "intern", type_="foreignkey")
    op.create_foreign_key(
        op.f("intern_user_id_fkey"), "intern", "user", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("intern_supervisor_id_fkey"),
        "intern",
        "supervisor",
        ["supervisor_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("intern_division_id_fkey"), "intern", "division", ["division_id"], ["id"]
    )
    op.drop_column("intern", "division_name")
    op.add_column(
        "administrator",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "administrator", type_="foreignkey")
    op.create_foreign_key(
        op.f("administrator_user_id_fkey"), "administrator", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
