"""refactor User model to contain division info

Revision ID: d9a4f802177c
Revises: f0ea3957b5e0
Create Date: 2025-09-08 12:17:04.086857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a4f802177c'
down_revision: Union[str, Sequence[str], None] = 'f0ea3957b5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('intern_division_name_fkey'), 'intern', type_='foreignkey')
    op.drop_column('intern', 'division_name')
    op.add_column('user', sa.Column('division_name', sa.String(), nullable=False, server_default="information_technology"))
    op.create_foreign_key(None, 'user', 'division', ['division_name'], ['name'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'division_name')
    op.add_column('intern', sa.Column('division_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('intern_division_name_fkey'), 'intern', 'division', ['division_name'], ['name'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
