"""major refactor of tables

Revision ID: db8074ba9d9d
Revises: ef008177a6e7
Create Date: 2025-09-08 09:45:17.746414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8074ba9d9d'
down_revision: Union[str, Sequence[str], None] = 'ef008177a6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skill_created_by_user_id_fkey'), 'skill', type_='foreignkey')
    op.drop_column('skill', 'created_by_user_id')
    op.drop_column('skill', 'description')
    op.add_column('task', sa.Column('supervisor_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'task', 'supervisor', ['supervisor_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'supervisor_id')
    op.add_column('skill', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skill', sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('skill_created_by_user_id_fkey'), 'skill', 'user', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###
