"""add new fields to User model

Revision ID: f0ea3957b5e0
Revises: 5b982fc26e62
Create Date: 2025-09-08 12:02:16.454741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.app_models import user_type_enum

# revision identifiers, used by Alembic.
revision: str = "f0ea3957b5e0"
down_revision: Union[str, Sequence[str], None] = "5b982fc26e62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("user", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "work_location", sa.String(), nullable=False, server_default="Falomo, Ikoyi"
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "type",
            sa.Enum("SUPERVISOR", "INTERN", "ADMIN", name="usertype"),
            nullable=False,
            server_default="INTERN",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "type")
    op.drop_column("user", "work_location")
    op.drop_column("user", "date_of_birth")

    user_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
