"""remove intern_supervisor_table

Revision ID: fe88785efeee
Revises: bf5d678d5912
Create Date: 2025-09-10 17:25:13.391256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe88785efeee'
down_revision: Union[str, Sequence[str], None] = 'bf5d678d5912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intern_supervisor')
    op.add_column('intern', sa.Column('supervisor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'intern', 'supervisor', ['supervisor_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intern', type_='foreignkey')
    op.drop_column('intern', 'supervisor_id')
    op.create_table('intern_supervisor',
    sa.Column('intern_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_assigned', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['intern.id'], name=op.f('intern_supervisor_intern_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.id'], name=op.f('intern_supervisor_supervisor_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intern_id', 'supervisor_id', name=op.f('intern_supervisor_pkey'))
    )
    # ### end Alembic commands ###
