from enum import StrEnum, Enum


class DepartmentEnum(Enum):
    CHIEF_EXECUTIVE_OFFICER_OFFICE = 0
    CHIEF_OPERATING_OFFICER_OFFICE_NG = 1
    COMPANY_SECRETARIAT = 2
    CORPORATE_SERVICES_AND_SUSTAINABILITY = 3
    CUSTOMER_RELATIONS_AND_EXPERIENCE = 4
    DIGITAL_SERVICES_NG = 5
    ENTERPRISE_BUSINESS = 6
    FINANCE = 7
    FIXED_BROADBAND = 8
    HUMAN_RESOURCES = 9
    INFORMATION_TECHNOLOGY = 10
    INTERNAL_AUDIT_AND_FORENSIC_SERVICES = 11
    MARKETING = 12
    NETWORK = 13
    RISK_AND_COMPLIANCE = 14
    SALES_AND_DISTRIBUTION = 15
    STRATEGY_AND_INNOVATION = 16


class UserType(StrEnum):
    SUPERVISOR = "supervisor"
    INTERN = "intern"
    ADMIN = "admin"
